### PR TITLE
Module 3 day 1 haseeb dev

### PR DESCRIPTION
**Pull request by abdulhaseebshaik**
Added 3 Task

### CODE REVIEW

**Comment by IshaaqhShaik** [comment]
@Saddamkhanlavani and @farooqgollapallishaik please review this tasks.

**Comment by Saddamkhanlavani** [comment]
Kindly complete 5th task as well.

**Comment by farooqgollapallishaik** [comment]
Reviewed by farooq

**Comment by MohammedArshad25** [comment]
Please add screenshot of the feature developed

**Review by IshaaqhShaik — APPROVED** [review]

**Pull request merged**
